
import "./globals.css";


export const metadata = {
  title: "Galsaa's personal portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-white">{children}</body>
    </html>
  );
}
